### ISSUE TITLE
Make a v1.3.0 tag?

### ISSUE THREAD

**Issue by baschny** [b13/distributed-locks#19]
Maybe its time to make a v1.3.0 tag? Seem pretty feature complete and stable, and now compatible with every imaginable PHP and TYPO3 versions:

https://github.com/b13/distributed-locks/compare/v1.2.0...master

Currently we have to require it at `dev-master` which always makes me shiver on a `composer update` seeing hashes being updated without any clue of what has changed. :)

**Comment by bmack** [comment]
Done!
