### ISSUE TITLE
TYPO3 v13 compatibility

### ISSUE THREAD

**Issue by JBlocks** [b13/distributed-locks#26]
In preparation for TYPO3 version 13, this repository / extension would also have to be adapted to the requirements. It has already happened in the b13/container extension.

Please make this extension compatible with TYPO3 v13.

**Comment by bmack** [comment]
just needs a tag now. Can you confirm it works properly in v13 on your setup? Betatesting helps :D

**Comment by JBlocks** [comment]
Just installed the dev-main and could not find any issues with T3 v13.1.1. 
Thanks for the patch.

**Comment by bmack** [comment]
2.0.0 release is out
