### ISSUE TITLE
TYPO3 10

### ISSUE THREAD

**Issue by robsonrobi** [b13/distributed-locks#7]
Hello.

We are currently using 2 typo3 instances, fileadmin, uploads are shared via nfs. A redis Server and a RDS is used. Currently we are struggling with files in /var/cache. This folder is also in nfs. Clearing the System Cache results in errietst, because one Instanzen tries to read, Schule the other writes i suspect. The error throws the SimpleFileBackend. Do you habe and advice, which folder i Need to Share over nfs. I am running TYPO3 10 the latest Version.

And help would be great .

**Comment by bmack** [comment]
Hey @robsonrobi ,

I don't think this is related to locking, but rather related to caching? If so, I suggest you open a ticket on stackoverflow or ask on #typo3-cms channel in TYPO3's Slack Workspace (see https://typo3.org/community/meet/how-to-use-slack-in-the-typo3-community).

This blog post of mine here might be of interest to you to get a good understanding of some troubles with NFS / File-based caches https://b13.com/blog/caching-in-typo3-part-3
