### ISSUE TITLE
What  to specify in 'database?'

### ISSUE THREAD

**Issue by bh-teufels** [b13/distributed-locks#8]
What  to specify in 'database?'

$GLOBALS['TYPO3_CONF_VARS']['SYS']['locking']['redis'] = [
    'hostname' => '127.0.0.1',
    'database' => 12
];

I see Examples with
 'database' => 8
 
 What is the value of 12 or 8?

**Comment by bmack** [comment]
@bh-teufels If you run Redis on your server, you can specify a number of databases (think of it like different "baskets" to store data in), and the difference between RDBMS and Redis is that Redis just uses a number as a "database name", starting from "0" as the first database. When configuring Redis on your server, you can specify the maximum amount of Redis databases that should be set up. Typically it is "16" or "32" by default, allowing any number from 0 to 15 / 31 to be available to be used as database.

In our TYPO3 setups, we usually have a number of caches configured to be used by Redis (e.g. pages, pagesection, cache_hash etc.) and the next one available we use for distributed locks as a separate database. This way, "clearing caches" does not touch the locks-store provided by Redis Backend.
